name: coffee_shop
description: "Coffee shop Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  shared_preferences: ^2.0.18
  image_picker: ^1.1.2

  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.8
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  flutter_inappwebview: ^5.7.2
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^5.0.6
  url_launcher: ^6.1.10






dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/espresso.jpg"

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/

